#!/bin/bash

echo "IP address: "
read ip

if [ ! -z $ip ]
then
  ping -c 1 $ip
  if [ $? -eq 0 ] ; then
    echo "Ping is responding"
  else
    echo "not ping"
  fi
else
  echo "IP address is empty"
fi



